
const ingredients = [
  { name: 'Rice', image: 'images/rice.png' },
  { name: 'Egg', image: 'images/egg.png' },
  { name: 'Chicken', image: 'images/chicken.png' },
  { name: 'Pasta', image: 'images/pasta.png' },
  { name: 'Bread', image: 'images/bread.png' },
  { name: 'Potato', image: 'images/potato.png' },
  { name: 'Apple', image: 'images/apple.png' },
  { name: 'Bean', image: 'images/bean.png' },
  { name: 'Shrimp', image: 'images/shrimp.png' },
  { name: 'Salmon', image: 'images/salmon.png' },
  { name: 'Avocado', image: 'images/avocado.png' },
  { name: 'Soy Sauce', image: 'images/soy sauce.png' },
  { name: 'Tomato', image: 'images/tomato.png' },
  { name: 'Bell Pepper', image: 'images/bell pepper.png' },
  { name: 'Lemon', image: 'images/lemon.png' },
  { name: 'Garlic', image: 'images/garlic.png' },
  { name: 'Wine', image: 'images/wine.png' },
  { name: 'Corn', image: 'images/corn.png' },
  { name: 'Tuna', image: 'images/tuna.png' },
  { name: 'Butter', image: 'images/butter.png' },
  { name: 'Olive Oil', image: 'images/olive oil.png' },
  { name: 'Cheese', image: 'images/cheese.png' },
  { name: 'Carrot', image: 'images/carrot.png' },
  { name: 'Spinach', image: 'images/spinach.png' },
  { name: 'Lettuce', image: 'images/lettuce.png' },
  { name: 'Mushroom', image: 'images/mushroom.png'},
  { name: 'Onion', image: 'images/onion.png' },
  { name: 'Cucumber', image: 'images/cucumber.png' },
  { name: 'Steak', image: 'images/steak.png' },
  { name: 'Pineapple', image: 'images/pineapple.png' },
  { name: 'Strawberry', image: 'images/strawberry.png' },
  { name: 'Blueberry', image: 'images/blueberry.png' },
  { name: 'Peach', image: 'images/peach.png' },
  { name: 'Raspberry', image: 'images/raspberry.png' },
  { name: 'Cherry', image: 'images/cherry.png' },
  { name: 'Watermelon', image: 'images/watermelon.png' },
  { name: 'Kiwi', image: 'images/kiwi.png' },
  { name: 'Grape', image: 'images/grape.png' },
  { name: 'Cabbage', image: 'images/cabbage.png' },
  { name: 'Broccoli', image: 'images/broccoli.png' },
  { name: 'Pine Nut', image: 'images/pinenut.png' },
  { name: 'Cilantro', image: 'images/cilantro.png' },
  { name: 'Peanut', image: 'images/peanut.png' },
  { name: 'Banana', image: 'images/banana.png' },
  { name: 'Cashew', image: 'images/cashew.png' },
  { name: 'Almond', image: 'images/almond.png' },
  { name: 'Hazelnut', image: 'images/hazelnut.png' },
  { name: 'Walnut', image: 'images/walnut.png' },
  { name: 'Chickpea', image: 'images/chickpea.png' },
  { name: 'Lentil', image: 'images/lentil.png' },
  { name: 'Tofu', image: 'images/tofu.png' },
  { name: 'Honey', image: 'images/honey.png' },
  { name: 'Maple Syrup', image: 'images/maplesyrup.png' },
  { name: 'Mustard', image: 'images/mustard.png' },
  { name: 'Mayonnaise', image: 'images/mayonnaise.png' },
  { name: 'Ketchup', image: 'images/ketchup.png' },
  { name: 'Ranch Dressing', image: 'images/ranch dressing.png' },
  { name: 'Sesame Seed', image: 'images/sesameseed.png' },
  { name: 'Honeydew Melon', image: 'images/honeydewmelon.png' },
  { name: 'Tofu', image: 'images/tofu.png' },
  { name: 'Cinnamon', image: 'images/cinnamon.png' },
  { name: 'Peach', image: 'images/peach.png' },
  { name: 'Cherry Tomato', image: 'images/cherry tomatoe.png' },
  { name: 'Pistachio', image: 'images/pistachio.png' },
  { name: 'Chilli', image: 'images/chilli.png' },
  { name: 'Eggplant', image: 'images/eggplant.png' },
  { name: 'Orange', image: 'images/orange.png' },
  { name: 'Pear', image: 'images/pear.png' },
  { name: 'Mango', image: 'images/mango.png' },
  { name: 'Coconut', image: 'images/coconut.png' },
  { name: 'Lobster', image: 'images/lobster.png' },
  { name: 'Sausage', image: 'images/sausage.png' },
  { name: 'Ham', image: 'images/ham.png' },
  { name: 'Scallop', image: 'images/scallop.png' },
  { name: 'Cinnamon', image: 'images/cinnamon.png' },
  { name: 'Dragon Fruit', image: 'images/dragon fruit.png' },
  { name: 'Dragon Fruit', image: 'images/dragon fruit.png' },
  { name: 'Ginger', image: 'images/ginger.png' },
  { name: 'Spring Onion', image: 'images/spring onion.png' },
  { name: 'Coriander', image: 'images/coriander.png' },
  { name: 'Ribs', image: 'images/rib.png' },
  { name: 'Squid', image: 'images/squid.png' },
  { name: 'Crab', image: 'images/crab.png' },
  { name: 'Wasabi', image: 'images/wasabi.png' },
  { name: 'Rambutan', image: 'images/rambutan.png' },
  { name: 'Rose Apple', image: 'images/rose apple.png' },
  { name: 'Olive', image: 'images/olive.png' },
  { name: 'Dill', image: 'images/dill.png' },
  { name: 'Yogurt', image: 'images/yogurt.png' },
  { name: 'Sugar', image: 'images/sugar.png' },
  { name: 'Caviar', image: 'images/caviar.png' },
  { name: 'Radish', image: 'images/radish.png' },
  { name: 'Kale', image: 'images/kale.png' },
  { name: 'pumpkin', image: 'images/pumpkin.png' },
  { name: 'Pickles', image: 'images/pickle.png' },
  { name: 'Oyster', image: 'images/oyster.png' },
  { name: 'Cantelope', image: 'images/cantelope.png' },
  { name: 'Durian', image: 'images/durian.png' },
  { name: 'Bacon', image: 'images/bacon.png' },
  { name: 'Papaya', image: 'images/papaya.png' },
  { name: 'Canned Tuna', image: 'images/canned tuna.png' },
  // { name: 'Dill', image: 'images/dill.png' },
  // { name: 'Dill', image: 'images/dill.png' },
  // { name: 'Dill', image: 'images/dill.png' },
  // { name: 'Dill', image: 'images/dill.png' },
  // { name: 'Dill', image: 'images/dill.png' },
  // { name: 'Dill', image: 'images/dill.png' },
];

export default ingredients